name: Variables
run-name: ¡Aprendiendo variables en github actions!
on:
  push
env:
  DIA_DE_SEMANA: Martes
jobs:
  dia:
    runs-on: ubuntu-latest
    steps:
      - name: Dia de semana
        run: echo El día de la semana es $DIA_DE_SEMANA
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo completo
        run: echo Hola, me llamo $NOMBRE y hoy es día $DIA_DE_SEMANA
